### PR TITLE
Package the code into .netstandard nuget package and clean-up the code

### PR DESCRIPTION
**Pull request by andy840119**
This pull request change something 
1. Package the code into .netstandard nuget package.
2. clean-up the code by Resharper.
.
I didn't change the code logic because i think this is perfect.
.
https://www.nuget.org/packages/MusixMatchAPI/1.0.0
and I upload this package into Nuget (because i need to use it right now)
if you want to add to the owner, or you want to delete it and upload yourself please contact with me : )
.
I'm not native speaker, so sorry for my bad English.

### CODE REVIEW

**Comment by jipjan** [comment]
Seems OK, good luck with the library!

**Comment by andy840119** [comment]
https://www.nuget.org/packages/MusixMatchAPI/1.0.0
If you have nuget account i can add you into owner.
Because i know most code is not mine.

**Comment by jipjan** [comment]
You can add me with username 'Eclipticus'

**Comment by andy840119** [comment]
Added : )

**Comment by jipjan** [comment]
I see, thanks!

**Pull request merged**
